apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ required "A valid .Values.Prefix entry required!" .Values.Prefix }}-fluentd-conf
  namespace: '{{ .Values.Release.Namespace }}'
data:
  fluentd.conf: |
{{ tpl (.Files.Get "fluentd/fluent.conf" | indent 4) .}}
# Rendering an external configuration file: https://helm.sh/docs/howto/charts_tips_and_tricks/
# since fluentd.conf is templatize too, we have to use tpl function.
