# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
Geneva:
  GCS:
    AuthIdType: "AuthMSIToken"
    Environment: "DiagnosticsProd"
    Account: "AzureMigrateExtProd"
    Namespace: "AzureMigrateExtProd"
    ConfigVersion: "1.7"
  MDM:
    Account: AzureMigrateExtProd

Fluentd:
  FilePathsCommaSeparated: "/var/log/containers/azuremigrate-springboot-controller-manager**manager**.log"

Prefix: "azuremigrate-springboot"

GenevaServiceAccount:
  Name: "azuremigrate-springboot-geneva-sa"

nameOverride: "springboot-azuremigrate-chart"
fullnameOverride: "springboot-azuremigrate-chart"
 
Release: # this value should match with what we provide during az-clusterextensioncreate
  Namespace: "springbootnamespace"  


#Below helm values will be provided by the extension manager(arc agentry) at parent chart level for e.g.
# helm install azure-springboot azure-springboot-$version.tgz  --create-namespace  --namespace=springbootnamespace --set Values.global.Azure.Extension.Name="myspringbootclusterextension".
#  Azure:
#    Extension:
#      Name: ""
#      ResourceId: ""
#    Cluster:
#      Region: ""
#    proxySettings:
#      httpProxy: ""
#      httpsProxy: ""
#      noProxy: ""  
#--------------------------------------------------------------------------------------------------