# Giving cluster level access, although we need rolebidning access to azure-arc and partnernamenamesapce to partnernameExtension inspite of partnername namesapce level access. 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  # namespace: '{{ .Values.Release.Namespace }}'
  name: "{{ .Values.Prefix }}-geneva-rolebinding"
subjects:
  - kind: ServiceAccount
    name: '{{ .Values.GenevaServiceAccount.Name }}'
    namespace: '{{ .Values.Release.Namespace }}'
roleRef:
  kind: ClusterRole
  name: "{{ .Values.Prefix }}-geneva-role"
  apiGroup: rbac.authorization.k8s.io